# Generated by Django 4.0.3 on 2022-04-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Marca', models.CharField(max_length=30)),
                ('Modelo', models.CharField(max_length=30)),
                ('Numero_de_serie', models.PositiveIntegerField(default=0)),
                ('Numero_de_motor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso_Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreOtipo', models.CharField(max_length=30)),
                ('FechaDeIngreso', models.DateField()),
                ('CantidadAIngresar', models.PositiveIntegerField(default=0)),
                ('NumeroDeParte', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('Legajo', models.PositiveIntegerField(default=0)),
                ('Email', models.EmailField(max_length=254)),
                ('Equipo_asignado', models.CharField(max_length=30)),
                ('profesion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trabajo_a_realizar', models.CharField(max_length=30)),
                ('Personal_Asignado', models.CharField(max_length=30)),
                ('Equipo', models.CharField(max_length=30)),
                ('Comienzo_de_trabajo', models.DateField()),
                ('Final_de_trabajo', models.DateField()),
            ],
        ),
    ]
