# Generated by Django 4.0.3 on 2022-04-25 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad_a_ingresar', models.PositiveIntegerField()),
                ('numero_de_parte', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=40)),
                ('personal_asignado', models.CharField(max_length=40)),
                ('nombre_equipo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ingreso_Materiales',
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='Numero_de_motor',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='Numero_de_serie',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Equipo_asignado',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Legajo',
        ),
        migrations.AddField(
            model_name='equipos',
            name='numero_de_motor',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipos',
            name='numero_de_serie',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='legajo',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
